---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2022-03-29T00:30:22Z"
  labels:
    kubernetes.io/metadata.name: kuttl-test-next-rat
  name: kuttl-test-next-rat
  resourceVersion: "10977225"
  uid: 047d1f6a-bd83-4491-b991-5023b32196b1
spec:
  finalizers:
  - kubernetes
status:
  phase: Active

---
