# permissions for end users to edit commons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: common-editor-role
rules:
- apiGroups:
  - enterprise.splunk.com
  resources:
  - commons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.com
  resources:
  - commons/status
  verbs:
  - get
