# permissions for end users to view commons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: common-viewer-role
rules:
- apiGroups:
  - enterprise.splunk.com
  resources:
  - commons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - enterprise.splunk.com
  resources:
  - commons/status
  verbs:
  - get
