
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - enterprise.splunk.com
  resources:
  - indexerclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.com
  resources:
  - indexerclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - enterprise.splunk.com
  resources:
  - licensemasters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.com
  resources:
  - licensemasters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - enterprise.splunk.com
  resources:
  - searchheadclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.com
  resources:
  - searchheadclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - enterprise.splunk.com
  resources:
  - standalones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.com
  resources:
  - standalones/status
  verbs:
  - get
  - patch
  - update
