apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "splunk-operator.labels" . | nindent 4 }}
  name: {{ include "splunk-operator.fullname" . }}-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    {{- include "splunk-operator.labels" . | nindent 4 }}
