{{- if .Values.splunkOperator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "splunk-operator.operator.fullname" . }}-controller-manager
  namespace: {{ include "splunk-operator.namespace" . }}
  labels:
    {{- include "splunk-operator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "splunk-operator.selectorLabels" . | nindent 6 }}
  strategy: 
    type: Recreate
  template:
    metadata:
      {{- with .Values.splunkOperator.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "splunk-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.splunkOperator.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "splunk-operator.operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.splunkOperator.securityContext | nindent 8 }}
      hostNetwork: {{ .Values.splunkOperator.hostNetwork }}
      hostPID: {{ .Values.splunkOperator.hostPID }}
      hostIPC: {{ .Values.splunkOperator.hostIPC }}
      containers:
        - name: kube-rbac-proxy
          image: "{{ .Values.kubeRbacProxy.image.repository }}:{{ .Values.kubeRbacProxy.image.tag }}"
          imagePullPolicy: {{ .Values.kubeRbacProxy.image.pullPolicy }}
          args:
          - "--secure-listen-address=0.0.0.0:8443"
          - "--upstream=http://127.0.0.1:8080/"
          - "--logtostderr=true"
          - "--v=10"
          ports:
          - containerPort: 8443
            name: https
        - name: manager
          securityContext:
            {{- toYaml .Values.splunkOperator.containerSecurityContext | nindent 12 }}
          image: "{{ .Values.splunkOperator.image.repository}}"
          imagePullPolicy: {{ .Values.splunkOperator.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
          - name: WATCH_NAMESPACE
          {{- if .Values.splunkOperator.watchNamespace }}          
            value: {{ .Values.splunkOperator.watchNamespace }}
          {{- else }}
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          {{- end }}          
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name          
          - name: OPERATOR_NAME
            value: {{ include "splunk-operator.operator.fullname" . }}     
          - name: RELATED_IMAGE_SPLUNK_ENTERPRISE
            value: "{{ .Values.image.repository}}"   
          ports:
            - containerPort: {{ .Values.splunkOperator.service.port}}
              name: http        
          resources:
            {{- toYaml .Values.splunkOperator.resources | nindent 12 }}
      {{- with .Values.splunkOperator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.splunkOperator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.splunkOperator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
{{- end }}