apiVersion: v1
kind: Service
metadata:
  name: {{ include "splunk-operator.operator.fullname" . }}-controller-manager-service
  labels:
{{- include "splunk-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.splunkOperator.service.type }}
  ports:   
    - name: http 
      port: {{ .Values.splunkOperator.service.httpPort }}
      protocol: TCP 
      targetPort: http 
{{- if .Values.splunkOperator.service.additionalPorts }}
{{ toYaml .Values.splunkOperator.service.additionalPorts | indent 4 }}
{{- end }}
  selector:
{{- include "splunk-operator.selectorLabels" . | nindent 4 }}