apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    marketplace.openshift.io/remote-workflow: https://marketplace.redhat.com/en-us/operators/splunk-operator/pricing?utm_source=openshift_console
    marketplace.openshift.io/support-workflow: https://marketplace.redhat.com/en-us/operators/splunk-operator/support?utm_source=openshift_console
  name: splunk-operator.v1.0.3
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ClusterMaster is the Schema for the clustermanagers API
      displayName: Cluster Master
      kind: ClusterMaster
      name: clustermasters.enterprise.splunk.com
      version: v3
    - description: IndexerCluster is the Schema for a Splunk Enterprise indexer cluster
      displayName: Indexer Cluster
      kind: IndexerCluster
      name: indexerclusters.enterprise.splunk.com
      version: v3
    - description: LicenseMaster is the Schema for a Splunk Enterprise license manager.
      displayName: License Master
      kind: LicenseMaster
      name: licensemasters.enterprise.splunk.com
      version: v3
    - description: MonitoringConsole is the Schema for the monitoringconsole API
      displayName: Monitoring Console
      kind: MonitoringConsole
      name: monitoringconsoles.enterprise.splunk.com
      version: v3
    - description: SearchHeadCluster is the Schema for a Splunk Enterprise search
        head cluster
      displayName: Search Head Cluster
      kind: SearchHeadCluster
      name: searchheadclusters.enterprise.splunk.com
      version: v3
    - description: Standalone is the Schema for a Splunk Enterprise standalone instances.
      displayName: Standalone
      kind: Standalone
      name: standalones.enterprise.splunk.com
      version: v3
  description: K8 Operator for Splunk Enterprise Deployments
  displayName: Splunk Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - splunk
  - enterprise
  - operator
  links:
  - name: Splunk Operator
    url: https://splunk-operator.domain
  maintainers:
  - email: docker-maint@splunk.com
    name: Splunk Docker Maintainers
  maturity: alpha
  provider:
    name: Splunk Inc.
    url: www.splunk.com
  version: 1.0.3
