- op: add
  path: "/spec/versions/-"
  value:
    name: v1
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
        description: SearchHeadCluster is the Schema for a Splunk Enterprise search API v1
        properties:
          apiVersion:
            type: string
- op: add
  path: "/spec/versions/-"
  value:
    name: v1alpha1
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
        description: SearchHeadCluster is the Schema for a Splunk Enterprise search API v1alpha1
        properties:
          apiVersion:
            type: string
- op: add
  path: "/spec/versions/-"
  value:
    name: v1beta1
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
        description: SearchHeadCluster is the Schema for a Splunk Enterprise search API v1beta1
        properties:
          apiVersion:
            type: string
- op: add
  path: "/spec/versions/-"
  value:
    name: v1beta2
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
        description: SearchHeadCluster is the Schema for a Splunk Enterprise search API v1beta2
        properties:
          apiVersion:
            type: string
- op: add
  path: "/spec/versions/-"
  value:
    name: v1beta3
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
        description: SearchHeadCluster is the Schema for a Splunk Enterprise search API v1beta3
        properties:
          apiVersion:
            type: string
- op: add
  path: "/spec/versions/-"
  value:
    name: v2
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
        description: SearchHeadCluster is the Schema for a Splunk Enterprise search API v2
        properties:
          apiVersion:
            type: string