- op: add
  path: "/spec/versions/-"
  value:
    name: v1
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
        description:  IndexerCluster is the Schema for a Splunk Enterprise indexer v1
        properties:
          apiVersion:
            type: string
- op: add
  path: "/spec/versions/-"
  value:
    name: v1alpha1
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
        description:  IndexerCluster is the Schema for a Splunk Enterprise indexer v1beta1
        properties:
          apiVersion:
            type: string
- op: add
  path: "/spec/versions/-"
  value:
    name: v1beta1
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
        description:  IndexerCluster is the Schema for a Splunk Enterprise indexer v1beta2
        properties:
          apiVersion:
            type: string
- op: add
  path: "/spec/versions/-"
  value:
    name: v1beta2
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
        properties:
          apiVersion:
            type: string
- op: add
  path: "/spec/versions/-"
  value:
    name: v1beta3
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
        description:  IndexerCluster is the Schema for a Splunk Enterprise indexer v1beta2
        properties:
          apiVersion:
            type: string
- op: add
  path: "/spec/versions/-"
  value:
    name: v2
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
        description:  IndexerCluster is the Schema for a Splunk Enterprise indexer v2
        properties:
          apiVersion:
            type: string