apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-licensemaster-editor-role
rules:
- apiGroups:
  - enterprise.splunk.com
  resources:
  - licensemasters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.com
  resources:
  - licensemasters/status
  verbs:
  - get
