apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "splunk-operator.fullname" . }}
  labels:
    {{- include "splunk-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "splunk-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "splunk-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "splunk-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: WATCH_NAMESPACE
          {{- if .Values.clusterScope }}          
            value:
          {{- else }}
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          {{- end }}          
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name          
          - name: OPERATOR_NAME
            value: "{{ include "splunk-operator.fullname" . }}"
          - name: RELATED_IMAGE_SPLUNK_ENTERPRISE
            value: "{{ .Values.splunkimage.repository }}:{{ .Values.splunkimage.tag }}"                
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
          {{- include "splunk-operator.selectorLabels" . | nindent 12 }}

