apiVersion: kuttl.dev/v1beta1
kind: TestSuite
testDirs:
- ./kuttl/tests/smoke
parallel: 1
timeout: 1000
startKIND: true
artifactsDir: kuttl-artifacts
kindNodeCache: true
commands:
  - command: bin/manager
    background: true