name: Merge Develop To Master Workflow
on: 
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version of Splunk Operator Release'
        required: true
jobs:
  pull-request:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - name: Reset master branch
      run: |
        git fetch origin develop:develop
        git reset --hard develop
    - name: Dotenv Action
      id: dotenv
      uses: falti/dotenv-action@d4d12eaa0e1dd06d5bdc3d7af3bf4c8c93cb5359
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3.10.1
      with:
        branch: "promote-develop-to-master-${{ github.event.inputs.release_version }}"
        base: "master"
        title: "Promote Develop to Master for Splunk Operator Release ${{ github.event.inputs.release_version }}"
        reviewers: "${{ steps.dotenv.outputs.REVIEWERS }}"
        body: |
          Automated Pull Request To Merge Develop To Master For Release Version ${{ github.event.inputs.release_version }}